/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Produced by backend/server/scripts/gen_pricing_ts.py from core/billing/catalog.py,
 * the same table that scripts/sync_dodo_prices.py pushes to Dodo. Editing this file
 * by hand reintroduces the drift it exists to prevent.
 *
 * Regenerate:  python scripts/gen_pricing_ts.py
 * Catalogue rev: cc32158   Countries: 109
 *
 * This is the OFFLINE FALLBACK only. The server decides the real price — it can see
 * the edge geo header, whereas the device only knows its own locale setting, which
 * a user can change in Settings.
 */

export interface CountryPricing {
  currency: string;
  monthly: number;
  yearly: number;
  monthlyLabel: string;
  yearlyLabel: string;
}

/** Charged to any country without a rule of its own — matches Dodo's base price. */
export const BASE_PRICING: CountryPricing = {
  currency: 'USD',
  monthly: 7.99,
  yearly: 79.99,
  monthlyLabel: '$7.99',
  yearlyLabel: '$79.99',
};

export const PRICING_BY_COUNTRY: Record<string, CountryPricing> = {
  AE: { currency: 'AED', monthly: 29, yearly: 299, monthlyLabel: 'AED 29', yearlyLabel: 'AED 299' },
  AM: { currency: 'AMD', monthly: 2990, yearly: 29900, monthlyLabel: '֏2,990', yearlyLabel: '֏29,900' },
  AR: { currency: 'USD', monthly: 4.99, yearly: 49.99, monthlyLabel: '$4.99', yearlyLabel: '$49.99' },
  AT: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  AU: { currency: 'AUD', monthly: 11.99, yearly: 119.99, monthlyLabel: 'A$11.99', yearlyLabel: 'A$119.99' },
  BA: { currency: 'BAM', monthly: 7.99, yearly: 79.99, monthlyLabel: 'KM 7.99', yearlyLabel: 'KM 79.99' },
  BD: { currency: 'BDT', monthly: 199, yearly: 1999, monthlyLabel: '৳199', yearlyLabel: '৳1,999' },
  BE: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  BG: { currency: 'EUR', monthly: 5.99, yearly: 59.99, monthlyLabel: '€5.99', yearlyLabel: '€59.99' },
  BH: { currency: 'BHD', monthly: 2.99, yearly: 29.90, monthlyLabel: 'BHD 2.99', yearlyLabel: 'BHD 29.90' },
  BM: { currency: 'USD', monthly: 7.99, yearly: 79.99, monthlyLabel: '$7.99', yearlyLabel: '$79.99' },
  BN: { currency: 'BND', monthly: 9.99, yearly: 99, monthlyLabel: 'B$9.99', yearlyLabel: 'B$99' },
  BO: { currency: 'BOB', monthly: 39, yearly: 399, monthlyLabel: 'Bs 39', yearlyLabel: 'Bs 399' },
  BR: { currency: 'BRL', monthly: 29.90, yearly: 299, monthlyLabel: 'R$29.90', yearlyLabel: 'R$299' },
  BS: { currency: 'BSD', monthly: 7.99, yearly: 79.99, monthlyLabel: 'B$7.99', yearlyLabel: 'B$79.99' },
  BW: { currency: 'BWP', monthly: 69, yearly: 690, monthlyLabel: 'BWP 69', yearlyLabel: 'BWP 690' },
  BZ: { currency: 'BZD', monthly: 15, yearly: 149, monthlyLabel: 'BZ$15', yearlyLabel: 'BZ$149' },
  CA: { currency: 'CAD', monthly: 10.99, yearly: 109.99, monthlyLabel: 'C$10.99', yearlyLabel: 'C$109.99' },
  CH: { currency: 'CHF', monthly: 7.99, yearly: 79.99, monthlyLabel: 'CHF 7.99', yearlyLabel: 'CHF 79.99' },
  CL: { currency: 'CLP', monthly: 5990, yearly: 59900, monthlyLabel: 'CLP 5,990', yearlyLabel: 'CLP 59,900' },
  CN: { currency: 'CNY', monthly: 49, yearly: 499, monthlyLabel: '¥49', yearlyLabel: '¥499' },
  CO: { currency: 'USD', monthly: 4.99, yearly: 49.99, monthlyLabel: '$4.99', yearlyLabel: '$49.99' },
  CR: { currency: 'CRC', monthly: 3990, yearly: 39900, monthlyLabel: '₡3,990', yearlyLabel: '₡39,900' },
  CY: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  CZ: { currency: 'CZK', monthly: 179, yearly: 1790, monthlyLabel: '179 Kč', yearlyLabel: '1,790 Kč' },
  DE: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  DK: { currency: 'DKK', monthly: 59, yearly: 599, monthlyLabel: '59 kr', yearlyLabel: '599 kr' },
  DO: { currency: 'DOP', monthly: 399, yearly: 3999, monthlyLabel: 'RD$399', yearlyLabel: 'RD$3,999' },
  EC: { currency: 'USD', monthly: 4.99, yearly: 49.99, monthlyLabel: '$4.99', yearlyLabel: '$49.99' },
  EE: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  EG: { currency: 'EGP', monthly: 249, yearly: 2490, monthlyLabel: 'EGP 249', yearlyLabel: 'EGP 2,490' },
  ES: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  ET: { currency: 'ETB', monthly: 499, yearly: 4990, monthlyLabel: 'ETB 499', yearlyLabel: 'ETB 4,990' },
  FI: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  FJ: { currency: 'FJD', monthly: 12.99, yearly: 129, monthlyLabel: 'FJ$12.99', yearlyLabel: 'FJ$129' },
  FR: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  GB: { currency: 'GBP', monthly: 6.99, yearly: 69.99, monthlyLabel: '£6.99', yearlyLabel: '£69.99' },
  GE: { currency: 'GEL', monthly: 19.90, yearly: 199, monthlyLabel: '₾19.90', yearlyLabel: '₾199' },
  GH: { currency: 'USD', monthly: 4.99, yearly: 49.99, monthlyLabel: '$4.99', yearlyLabel: '$49.99' },
  GR: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  GT: { currency: 'GTQ', monthly: 59, yearly: 599, monthlyLabel: 'Q59', yearlyLabel: 'Q599' },
  HK: { currency: 'HKD', monthly: 59, yearly: 599, monthlyLabel: 'HK$59', yearlyLabel: 'HK$599' },
  HN: { currency: 'HNL', monthly: 199, yearly: 1999, monthlyLabel: 'L199', yearlyLabel: 'L1,999' },
  HR: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  HU: { currency: 'HUF', monthly: 2490, yearly: 24900, monthlyLabel: '2,490 Ft', yearlyLabel: '24,900 Ft' },
  ID: { currency: 'IDR', monthly: 49000, yearly: 490000, monthlyLabel: 'Rp49,000', yearlyLabel: 'Rp490,000' },
  IE: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  IL: { currency: 'ILS', monthly: 29, yearly: 299, monthlyLabel: '₪29', yearlyLabel: '₪299' },
  IN: { currency: 'INR', monthly: 149, yearly: 999, monthlyLabel: '₹149', yearlyLabel: '₹999' },
  IQ: { currency: 'IQD', monthly: 7500, yearly: 75000, monthlyLabel: 'IQD 7,500', yearlyLabel: 'IQD 75,000' },
  IS: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  IT: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  JO: { currency: 'JOD', monthly: 5.49, yearly: 54.90, monthlyLabel: 'JOD 5.49', yearlyLabel: 'JOD 54.90' },
  JP: { currency: 'JPY', monthly: 1000, yearly: 9900, monthlyLabel: '¥1,000', yearlyLabel: '¥9,900' },
  KE: { currency: 'USD', monthly: 3.99, yearly: 39.99, monthlyLabel: '$3.99', yearlyLabel: '$39.99' },
  KR: { currency: 'KRW', monthly: 9900, yearly: 99000, monthlyLabel: '₩9,900', yearlyLabel: '₩99,000' },
  KW: { currency: 'KWD', monthly: 2.49, yearly: 24.90, monthlyLabel: 'KWD 2.49', yearlyLabel: 'KWD 24.90' },
  KZ: { currency: 'KZT', monthly: 3990, yearly: 39900, monthlyLabel: '₸3,990', yearlyLabel: '₸39,900' },
  LB: { currency: 'USD', monthly: 3.99, yearly: 39.99, monthlyLabel: '$3.99', yearlyLabel: '$39.99' },
  LK: { currency: 'LKR', monthly: 999, yearly: 9999, monthlyLabel: 'LKR 999', yearlyLabel: 'LKR 9,999' },
  LT: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  LU: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  LV: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  MA: { currency: 'MAD', monthly: 49, yearly: 490, monthlyLabel: 'MAD 49', yearlyLabel: 'MAD 490' },
  MG: { currency: 'USD', monthly: 2.99, yearly: 29.99, monthlyLabel: '$2.99', yearlyLabel: '$29.99' },
  MK: { currency: 'MKD', monthly: 399, yearly: 3990, monthlyLabel: 'MKD 399', yearlyLabel: 'MKD 3,990' },
  MT: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  MU: { currency: 'MUR', monthly: 199, yearly: 1990, monthlyLabel: 'MUR 199', yearlyLabel: 'MUR 1,990' },
  MV: { currency: 'MVR', monthly: 99, yearly: 999, monthlyLabel: 'MVR 99', yearlyLabel: 'MVR 999' },
  MX: { currency: 'MXN', monthly: 99, yearly: 999, monthlyLabel: 'MX$99', yearlyLabel: 'MX$999' },
  MY: { currency: 'MYR', monthly: 19.90, yearly: 199, monthlyLabel: 'RM19.90', yearlyLabel: 'RM199' },
  NA: { currency: 'USD', monthly: 4.99, yearly: 49.99, monthlyLabel: '$4.99', yearlyLabel: '$49.99' },
  NG: { currency: 'NGN', monthly: 4999, yearly: 49990, monthlyLabel: '₦4,999', yearlyLabel: '₦49,990' },
  NL: { currency: 'EUR', monthly: 7.99, yearly: 79.99, monthlyLabel: '€7.99', yearlyLabel: '€79.99' },
  NO: { currency: 'NOK', monthly: 79, yearly: 799, monthlyLabel: '79 kr', yearlyLabel: '799 kr' },
  NP: { currency: 'NPR', monthly: 399, yearly: 3999, monthlyLabel: 'NPR 399', yearlyLabel: 'NPR 3,999' },
  NZ: { currency: 'NZD', monthly: 12.99, yearly: 129.99, monthlyLabel: 'NZ$12.99', yearlyLabel: 'NZ$129.99' },
  OM: { currency: 'OMR', monthly: 2.49, yearly: 24.90, monthlyLabel: 'OMR 2.49', yearlyLabel: 'OMR 24.90' },
  PE: { currency: 'PEN', monthly: 19.90, yearly: 199, monthlyLabel: 'S/19.90', yearlyLabel: 'S/199' },
  PG: { currency: 'PGK', monthly: 39, yearly: 390, monthlyLabel: 'PGK 39', yearlyLabel: 'PGK 390' },
  PH: { currency: 'PHP', monthly: 249, yearly: 2490, monthlyLabel: '₱249', yearlyLabel: '₱2,490' },
  PK: { currency: 'USD', monthly: 1.99, yearly: 19.99, monthlyLabel: '$1.99', yearlyLabel: '$19.99' },
  PL: { currency: 'PLN', monthly: 29.99, yearly: 299, monthlyLabel: '29.99 zł', yearlyLabel: '299 zł' },
  PT: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  PY: { currency: 'PYG', monthly: 29900, yearly: 299000, monthlyLabel: '₲29,900', yearlyLabel: '₲299,000' },
  QA: { currency: 'QAR', monthly: 29, yearly: 299, monthlyLabel: 'QAR 29', yearlyLabel: 'QAR 299' },
  RO: { currency: 'RON', monthly: 34.99, yearly: 349.99, monthlyLabel: '34.99 lei', yearlyLabel: '349.99 lei' },
  RS: { currency: 'RSD', monthly: 699, yearly: 6990, monthlyLabel: 'RSD 699', yearlyLabel: 'RSD 6,990' },
  SA: { currency: 'SAR', monthly: 29, yearly: 299, monthlyLabel: 'SAR 29', yearlyLabel: 'SAR 299' },
  SB: { currency: 'SBD', monthly: 39, yearly: 390, monthlyLabel: 'SBD 39', yearlyLabel: 'SBD 390' },
  SC: { currency: 'SCR', monthly: 79, yearly: 790, monthlyLabel: 'SCR 79', yearlyLabel: 'SCR 790' },
  SE: { currency: 'SEK', monthly: 79, yearly: 799, monthlyLabel: '79 kr', yearlyLabel: '799 kr' },
  SG: { currency: 'SGD', monthly: 9.99, yearly: 99.99, monthlyLabel: 'S$9.99', yearlyLabel: 'S$99.99' },
  SI: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  SK: { currency: 'EUR', monthly: 6.99, yearly: 69.99, monthlyLabel: '€6.99', yearlyLabel: '€69.99' },
  TH: { currency: 'THB', monthly: 199, yearly: 1990, monthlyLabel: '฿199', yearlyLabel: '฿1,990' },
  TO: { currency: 'TOP', monthly: 19, yearly: 190, monthlyLabel: 'TOP 19', yearlyLabel: 'TOP 190' },
  TR: { currency: 'TRY', monthly: 149, yearly: 1490, monthlyLabel: '₺149', yearlyLabel: '₺1,490' },
  TW: { currency: 'TWD', monthly: 249, yearly: 2490, monthlyLabel: 'NT$249', yearlyLabel: 'NT$2,490' },
  TZ: { currency: 'TZS', monthly: 9900, yearly: 99000, monthlyLabel: 'TZS 9,900', yearlyLabel: 'TZS 99,000' },
  UG: { currency: 'USD', monthly: 3.99, yearly: 39.99, monthlyLabel: '$3.99', yearlyLabel: '$39.99' },
  US: { currency: 'USD', monthly: 7.99, yearly: 79.99, monthlyLabel: '$7.99', yearlyLabel: '$79.99' },
  UY: { currency: 'UYU', monthly: 299, yearly: 2990, monthlyLabel: 'UYU 299', yearlyLabel: 'UYU 2,990' },
  VE: { currency: 'USD', monthly: 3.99, yearly: 39.99, monthlyLabel: '$3.99', yearlyLabel: '$39.99' },
  VN: { currency: 'VND', monthly: 79000, yearly: 790000, monthlyLabel: '₫79,000', yearlyLabel: '₫790,000' },
  VU: { currency: 'VUV', monthly: 799, yearly: 7990, monthlyLabel: 'VUV 799', yearlyLabel: 'VUV 7,990' },
  WS: { currency: 'WST', monthly: 19, yearly: 190, monthlyLabel: 'WST 19', yearlyLabel: 'WST 190' },
  ZA: { currency: 'ZAR', monthly: 99, yearly: 999, monthlyLabel: 'R99', yearlyLabel: 'R999' },
  ZM: { currency: 'ZMW', monthly: 49, yearly: 490, monthlyLabel: 'ZMW 49', yearlyLabel: 'ZMW 490' },
};

export function pricingForCountry(code?: string | null): CountryPricing {
  if (!code) return BASE_PRICING;
  return PRICING_BY_COUNTRY[code.toUpperCase()] ?? BASE_PRICING;
}

/** IANA time zone (lowercased) -> ISO-3166 country, for catalogue countries. */
export const COUNTRY_BY_TIMEZONE: Record<string, string> = {
  'africa/accra': 'GH',
  'africa/addis_ababa': 'ET',
  'africa/cairo': 'EG',
  'africa/casablanca': 'MA',
  'africa/ceuta': 'ES',
  'africa/dar_es_salaam': 'TZ',
  'africa/gaborone': 'BW',
  'africa/johannesburg': 'ZA',
  'africa/kampala': 'UG',
  'africa/lagos': 'NG',
  'africa/lusaka': 'ZM',
  'africa/nairobi': 'KE',
  'africa/windhoek': 'NA',
  'america/adak': 'US',
  'america/anchorage': 'US',
  'america/araguaina': 'BR',
  'america/argentina/buenos_aires': 'AR',
  'america/argentina/catamarca': 'AR',
  'america/argentina/cordoba': 'AR',
  'america/argentina/jujuy': 'AR',
  'america/argentina/la_rioja': 'AR',
  'america/argentina/mendoza': 'AR',
  'america/argentina/rio_gallegos': 'AR',
  'america/argentina/salta': 'AR',
  'america/argentina/san_juan': 'AR',
  'america/argentina/san_luis': 'AR',
  'america/argentina/tucuman': 'AR',
  'america/argentina/ushuaia': 'AR',
  'america/asuncion': 'PY',
  'america/atikokan': 'CA',
  'america/bahia': 'BR',
  'america/bahia_banderas': 'MX',
  'america/belem': 'BR',
  'america/belize': 'BZ',
  'america/blanc-sablon': 'CA',
  'america/boa_vista': 'BR',
  'america/bogota': 'CO',
  'america/boise': 'US',
  'america/buenos_aires': 'AR',
  'america/cambridge_bay': 'CA',
  'america/campo_grande': 'BR',
  'america/cancun': 'MX',
  'america/caracas': 'VE',
  'america/catamarca': 'AR',
  'america/chicago': 'US',
  'america/chihuahua': 'MX',
  'america/ciudad_juarez': 'MX',
  'america/cordoba': 'AR',
  'america/costa_rica': 'CR',
  'america/coyhaique': 'CL',
  'america/creston': 'CA',
  'america/cuiaba': 'BR',
  'america/dawson': 'CA',
  'america/dawson_creek': 'CA',
  'america/denver': 'US',
  'america/detroit': 'US',
  'america/edmonton': 'CA',
  'america/eirunepe': 'BR',
  'america/fort_nelson': 'CA',
  'america/fortaleza': 'BR',
  'america/glace_bay': 'CA',
  'america/goose_bay': 'CA',
  'america/guatemala': 'GT',
  'america/guayaquil': 'EC',
  'america/halifax': 'CA',
  'america/hermosillo': 'MX',
  'america/indiana/indianapolis': 'US',
  'america/indiana/knox': 'US',
  'america/indiana/marengo': 'US',
  'america/indiana/petersburg': 'US',
  'america/indiana/tell_city': 'US',
  'america/indiana/vevay': 'US',
  'america/indiana/vincennes': 'US',
  'america/indiana/winamac': 'US',
  'america/inuvik': 'CA',
  'america/iqaluit': 'CA',
  'america/jujuy': 'AR',
  'america/juneau': 'US',
  'america/kentucky/louisville': 'US',
  'america/kentucky/monticello': 'US',
  'america/la_paz': 'BO',
  'america/lima': 'PE',
  'america/los_angeles': 'US',
  'america/maceio': 'BR',
  'america/manaus': 'BR',
  'america/matamoros': 'MX',
  'america/mazatlan': 'MX',
  'america/mendoza': 'AR',
  'america/menominee': 'US',
  'america/merida': 'MX',
  'america/metlakatla': 'US',
  'america/mexico_city': 'MX',
  'america/moncton': 'CA',
  'america/monterrey': 'MX',
  'america/montevideo': 'UY',
  'america/nassau': 'BS',
  'america/new_york': 'US',
  'america/nome': 'US',
  'america/noronha': 'BR',
  'america/north_dakota/beulah': 'US',
  'america/north_dakota/center': 'US',
  'america/north_dakota/new_salem': 'US',
  'america/ojinaga': 'MX',
  'america/phoenix': 'US',
  'america/porto_velho': 'BR',
  'america/punta_arenas': 'CL',
  'america/rankin_inlet': 'CA',
  'america/recife': 'BR',
  'america/regina': 'CA',
  'america/resolute': 'CA',
  'america/rio_branco': 'BR',
  'america/rosario': 'AR',
  'america/santarem': 'BR',
  'america/santiago': 'CL',
  'america/santo_domingo': 'DO',
  'america/sao_paulo': 'BR',
  'america/sitka': 'US',
  'america/st_johns': 'CA',
  'america/swift_current': 'CA',
  'america/tegucigalpa': 'HN',
  'america/tijuana': 'MX',
  'america/toronto': 'CA',
  'america/vancouver': 'CA',
  'america/whitehorse': 'CA',
  'america/winnipeg': 'CA',
  'america/yakutat': 'US',
  'antarctica/macquarie': 'AU',
  'asia/almaty': 'KZ',
  'asia/amman': 'JO',
  'asia/aqtau': 'KZ',
  'asia/aqtobe': 'KZ',
  'asia/atyrau': 'KZ',
  'asia/baghdad': 'IQ',
  'asia/bahrain': 'BH',
  'asia/bangkok': 'TH',
  'asia/beirut': 'LB',
  'asia/brunei': 'BN',
  'asia/calcutta': 'IN',
  'asia/chongqing': 'CN',
  'asia/chungking': 'CN',
  'asia/colombo': 'LK',
  'asia/dacca': 'BD',
  'asia/dhaka': 'BD',
  'asia/dubai': 'AE',
  'asia/famagusta': 'CY',
  'asia/harbin': 'CN',
  'asia/ho_chi_minh': 'VN',
  'asia/hong_kong': 'HK',
  'asia/istanbul': 'TR',
  'asia/jakarta': 'ID',
  'asia/jayapura': 'ID',
  'asia/jerusalem': 'IL',
  'asia/karachi': 'PK',
  'asia/kathmandu': 'NP',
  'asia/katmandu': 'NP',
  'asia/kolkata': 'IN',
  'asia/kuala_lumpur': 'MY',
  'asia/kuching': 'MY',
  'asia/kuwait': 'KW',
  'asia/makassar': 'ID',
  'asia/manila': 'PH',
  'asia/muscat': 'OM',
  'asia/nicosia': 'CY',
  'asia/oral': 'KZ',
  'asia/pontianak': 'ID',
  'asia/qatar': 'QA',
  'asia/qostanay': 'KZ',
  'asia/qyzylorda': 'KZ',
  'asia/riyadh': 'SA',
  'asia/saigon': 'VN',
  'asia/seoul': 'KR',
  'asia/shanghai': 'CN',
  'asia/singapore': 'SG',
  'asia/taipei': 'TW',
  'asia/tbilisi': 'GE',
  'asia/tokyo': 'JP',
  'asia/urumqi': 'CN',
  'asia/yerevan': 'AM',
  'atlantic/azores': 'PT',
  'atlantic/bermuda': 'BM',
  'atlantic/canary': 'ES',
  'atlantic/madeira': 'PT',
  'atlantic/reykjavik': 'IS',
  'australia/adelaide': 'AU',
  'australia/brisbane': 'AU',
  'australia/broken_hill': 'AU',
  'australia/darwin': 'AU',
  'australia/eucla': 'AU',
  'australia/hobart': 'AU',
  'australia/lindeman': 'AU',
  'australia/lord_howe': 'AU',
  'australia/melbourne': 'AU',
  'australia/perth': 'AU',
  'australia/sydney': 'AU',
  'egypt': 'EG',
  'eire': 'IE',
  'europe/amsterdam': 'NL',
  'europe/athens': 'GR',
  'europe/belgrade': 'RS',
  'europe/berlin': 'DE',
  'europe/bratislava': 'SK',
  'europe/brussels': 'BE',
  'europe/bucharest': 'RO',
  'europe/budapest': 'HU',
  'europe/busingen': 'DE',
  'europe/copenhagen': 'DK',
  'europe/dublin': 'IE',
  'europe/helsinki': 'FI',
  'europe/istanbul': 'TR',
  'europe/lisbon': 'PT',
  'europe/ljubljana': 'SI',
  'europe/london': 'GB',
  'europe/luxembourg': 'LU',
  'europe/madrid': 'ES',
  'europe/malta': 'MT',
  'europe/nicosia': 'CY',
  'europe/oslo': 'NO',
  'europe/paris': 'FR',
  'europe/prague': 'CZ',
  'europe/riga': 'LV',
  'europe/rome': 'IT',
  'europe/sarajevo': 'BA',
  'europe/skopje': 'MK',
  'europe/sofia': 'BG',
  'europe/stockholm': 'SE',
  'europe/tallinn': 'EE',
  'europe/vienna': 'AT',
  'europe/vilnius': 'LT',
  'europe/warsaw': 'PL',
  'europe/zagreb': 'HR',
  'europe/zurich': 'CH',
  'gb': 'GB',
  'gb-eire': 'GB',
  'hongkong': 'HK',
  'indian/antananarivo': 'MG',
  'indian/mahe': 'SC',
  'indian/maldives': 'MV',
  'indian/mauritius': 'MU',
  'israel': 'IL',
  'japan': 'JP',
  'nz': 'NZ',
  'pacific/apia': 'WS',
  'pacific/auckland': 'NZ',
  'pacific/bougainville': 'PG',
  'pacific/chatham': 'NZ',
  'pacific/easter': 'CL',
  'pacific/efate': 'VU',
  'pacific/fiji': 'FJ',
  'pacific/galapagos': 'EC',
  'pacific/guadalcanal': 'SB',
  'pacific/honolulu': 'US',
  'pacific/port_moresby': 'PG',
  'pacific/tongatapu': 'TO',
  'poland': 'PL',
  'portugal': 'PT',
  'prc': 'CN',
  'roc': 'TW',
  'rok': 'KR',
  'singapore': 'SG',
  'turkey': 'TR',
};

export function countryForTimeZone(tz?: string | null): string | null {
  if (!tz) return null;
  return COUNTRY_BY_TIMEZONE[tz.toLowerCase()] ?? null;
}
